'use strict';
const $=id=>document.getElementById(id);
const labels={recordings:'ক্লাস রেকর্ডিং',classes:'ক্লাস ও ভিডিও',documents:'নোট ও ডকুমেন্ট',tools:'টুলস ও সেটআপ',information:'তথ্য ও নির্দেশনা',notices:'নোটিশ'};
const pageNames={overview:'ড্যাশবোর্ড',classes:'সব ক্লাস',resources:'রিসোর্স লাইব্রেরি',tools:'টুলস ও সেটআপ',schedule:'সময়সূচি',notices:'নোটিশ ও তথ্য',about:'আর্কাইভ সম্পর্কে',class:'ক্লাসের বিস্তারিত',resource:'রিসোর্সের বিস্তারিত'};
let archive,entries=[],filterCategory='',currentPage='overview',toastTimer;
const bn=n=>new Intl.NumberFormat('bn-BD').format(n);
function date(d,year=true){if(!d||!/^\d{4}-\d{2}-\d{2}$/.test(d))return 'তারিখ যাচাই বাকি';const value=new Date(d+'T00:00:00Z');return Number.isFinite(value.getTime())?new Intl.DateTimeFormat('bn-BD',{day:'numeric',month:'long',...(year?{year:'numeric'}:{}),timeZone:'UTC'}).format(value):'তারিখ যাচাই বাকি';}
function classDateLabel(e,year=true){const d=e.classDate||e.date,label=date(d,year);if(e.category!=='recordings'||!d||label==='তারিখ যাচাই বাকি')return label;return label+' · '+new Intl.DateTimeFormat('bn-BD',{weekday:'long',timeZone:'UTC'}).format(new Date(d+'T00:00:00Z'));}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined&&text!==null)e.textContent=text;if(cls)e.className=cls;return e;}
function append(parent,...children){parent.append(...children.filter(Boolean));return parent;}
function internal(href,text,cls){const a=node('a',text,cls);a.href=href;return a;}
function safeURL(value){if(typeof value!=='string'||!value.trim())return null;try{const u=new URL(value,location.origin);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null;}catch{return null;}}
function safeDocumentURL(value){const u=safeURL(value);if(!u)return null;const url=new URL(u);return url.origin===location.origin&&/\.pdf$/i.test(url.pathname)?url.href:null;}
function external(url,text,cls='resource-link'){const u=safeURL(url);if(!u)return node('span','লিংক যোগ করার অপেক্ষায়','muted');const a=node('a',text,cls);a.href=u;a.target='_blank';a.rel='noopener noreferrer';return a;}
function button(text,handler,cls='button'){const b=node('button',text,cls);b.type='button';b.onclick=handler;return b;}
function isNoteResource(e){return !!e.noteText||((e.resourceKinds||[]).includes('notes')&&!!(e.documentUrl||e.text));}
function isToolResource(e){return e.category==='tools'||(e.resourceKinds||[]).includes('tools');}
function hasResourceKind(e,kind){return kind==='tools'?isToolResource(e):e.category===kind||(e.resourceKinds||[]).includes(kind);}
function records(){return entries.filter(e=>e.category==='recordings').sort((a,b)=>(a.recordingSerial||999)-(b.recordingSerial||999));}
function title(e){return e.topicTitle||e.title;}
function resourceHash(e){return '#'+(e.category==='recordings'?'class/':'resource/')+e.id;}
function status(e){if(e.archivedRecordingId){const original=entries.find(x=>x.id===e.archivedRecordingId&&x.category==='recordings');if(original)return status(original);}if((e.dailymotionVideos||[]).length)return {text:e.dailymotionVideos.every(v=>v.playbackVerified)?'ভিডিও প্রস্তুত':'ভিডিও প্রস্তুত হচ্ছে',cls:e.dailymotionVideos.every(v=>v.playbackVerified)?'ready':'pending'};if(e.videoStatus==='upload-blocked-dailymotion-limit')return {text:'আপলোড সীমা রিসেটের অপেক্ষায়',cls:'pending'};if(e.videoStatus==='upload-blocked-dailymotion-error')return {text:'আপলোড পুনরায় চেষ্টা বাকি',cls:'pending'};if(e.videoStatus==='upload-blocked-daily-limit')return {text:'YouTube আপলোড অপেক্ষায়',cls:'pending'};if(e.youtubeId)return {text:'ভিডিও প্রস্তুত',cls:'ready'};if(e.videoStatus==='uploading'||e.videoStatus==='uploaded-processing')return {text:'ভিডিও প্রস্তুত হচ্ছে',cls:'pending'};if(e.category==='recordings'||(e.videoStatus||'').startsWith('upload-'))return {text:'ভিডিও পরে যোগ হবে',cls:'pending'};return {text:e.noteText?'নোট পড়া যাবে':'রিসোর্স',cls:''};}

function dailymotionClips(e){return (e.dailymotionVideos||[]).filter(v=>/^[A-Za-z0-9]{5,40}$/.test(v.privateId||(v.visibility==='public'?v.videoId:'')||''));}
function verifiedVideoCount(){const ids=new Set();for(const e of entries){if(e.playbackVerified&&e.youtubeId)ids.add('youtube:'+e.youtubeId);for(const v of e.dailymotionVideos||[])if(v.playbackVerified&&v.videoId)ids.add('dailymotion:'+v.videoId);}return ids.size;}
function dailymotionPlayer(e,parent){const clips=dailymotionClips(e);if(!clips.length)return false;const frame=node('iframe',null,'player');frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';const actions=node('div',null,'hero-actions'),buttons=[];function select(clip){const id=clip.privateId||clip.videoId;frame.src='https://geo.dailymotion.com/player/x1o0xy.html?video='+encodeURIComponent(id)+'&autoplay=false';frame.title=title(e)+' · '+(clip.label||'ভিডিও');buttons.forEach(({b,v})=>{const active=v===clip;b.classList.toggle('primary',active);b.setAttribute('aria-pressed',String(active));});}if(clips.length>1){for(const clip of clips){const b=button(clip.label||('অংশ '+bn(buttons.length+1)),()=>select(clip));buttons.push({b,v:clip});actions.append(b);}parent.append(actions);}select(clips[0]);parent.append(frame);if(!clips.every(v=>v.playbackVerified))parent.append(strip('কিছু ভিডিওর প্রসেসিং বা প্লেব্যাক যাচাই চলছে। প্রস্তুত অংশগুলো এখানেই দেখা যাবে।'));return true;}

function badge(e){const s=status(e);return node('span',s.text,'badge '+s.cls);}
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').hidden=true;},4500);}
function heading(label,h1,description,count){const div=node('div',null,'page-heading');const copy=node('div');append(copy,node('div',label,'eyebrow'),node('h1',h1),description?node('p',description):null);div.append(copy);if(count!==undefined)div.append(node('span',count,'count-pill'));$('page').append(div);}
function sectionHeading(text,href,linkText){const s=node('div',null,'section-heading');s.append(node('h2',text));if(href)s.append(internal(href,linkText||'সব দেখুন ↗','text-link'));return s;}
function strip(text){return append(node('aside',null,'notice-strip'),node('span','◈'),node('p',text));}
function slot(label,description,kind,id,filled=false){const box=node('section',null,'resource-slot'+(filled?' filled':''));const top=node('div',null,'slot-title');append(top,node('span',({video:'▷',note:'≡',document:'▧',tool:'⌘'})[kind]||'＋','slot-icon'),node('h3',label));append(box,top,node('p',description));return box;}
function empty(label,text,href){const e=append(node('div',null,'empty-state'),node('span','▧','empty-icon'),node('h3',label),node('p',text));if(href)e.append(internal(href,'রিসোর্স যোগ করার অপশন ↗','button'));return e;}
function classRow(e,compact=false){const a=internal(resourceHash(e),null,'class-row');const main=node('div',null,'class-main');append(main,node('h3',title(e)),append(node('div',null,'class-meta'),node('span',classDateLabel(e,false)),!compact&&e.duration?node('span',e.duration):null,!compact&&e.topic?node('span',e.topic):null));append(a,node('span',String(e.recordingSerial||'').padStart(2,'0'),'class-number'),main,!compact?badge(e):null,node('span','↗','row-arrow'));return a;}
function card(e){const c=node('article',null,'resource-card');append(c,node('span',labels[e.category]||'রিসোর্স','badge'),node('h3',title(e)),node('p',(e.text||'রিসোর্সের বিস্তারিত তথ্য পরে যোগ হবে।').replace(/\s+/g,' ').slice(0,130)+((e.text||'').length>130?'…':'')));append(c,append(node('div',null,'card-foot'),node('span',classDateLabel(e,false)),internal(resourceHash(e),'বিস্তারিত ↗','text-link')));return c;}
function weekly(compact=false){const s=node('div',null,compact?'':'schedule-large');for(const [short,day,time,info]of [['শুক্র','শুক্রবার','রাত ৯:৩০–১১:৩০','নিয়মিত ক্লাস'],['রবি','রবিবার','রাত ৯:৩০–১১:৩০','নিয়মিত ক্লাস'],['মঙ্গল','মঙ্গলবার','সন্ধ্যা ৭টা–রাত ১টা','প্র্যাকটিস ও সাপোর্ট']]){const a=node(compact?'div':'article',null,compact?'schedule-day':'');if(compact){append(a,node('span',short,'day-block'),append(node('div'),node('strong',day),node('p',time+' · '+info)));}else append(a,node('span',info,'eyebrow'),node('h3',day),node('strong',time),node('p','অফিশিয়াল ব্যাচের সাপ্তাহিক সময়সূচি'));s.append(a);}return s;}
function adPlacement(id){const a=node('aside',null,'sponsor-slot placement-ad placement-'+id);a.dataset.adPosition=id;a.setAttribute('aria-label','বিজ্ঞাপন');a.hidden=true;return a;}
function overview(){const hero=node('section',null,'hero');const copy=node('div',null,'hero-copy');const h=node('h1');append(h,document.createTextNode('একটি ব্যাচ।'),node('br'),node('span','শেখার সবকিছু এক জায়গায়।'));append(copy,node('div','YOUR WEB SECURITY JOURNEY','eyebrow'),h,node('p','শুরু থেকে ধারাবাহিকভাবে ক্লাস দেখুন। প্রতিটি ক্লাসের সঙ্গে নোট, ডকুমেন্ট ও প্রয়োজনীয় টুলস খুঁজে নিন।'),append(node('div',null,'hero-actions'),internal('#classes','ক্লাস শুরু করুন →','button primary'),internal('#resources','রিসোর্স লাইব্রেরি','button ghost')));const art=node('div',null,'hero-art');art.setAttribute('aria-hidden','true');append(art,node('div',null,'orbit'),node('span','Δ','delta-glyph'),node('span','WEB SECURITY','floating-chip chip-one'),node('span','< learn / practice >','floating-chip chip-two'),node('span','BATCH 66 · DELTA','floating-chip chip-three'));append(hero,copy,art);$('page').append(hero);
 const stats=node('section',null,'stat-grid');stats.setAttribute('aria-label','আর্কাইভের পরিসংখ্যান');for(const [value,label,symbol]of [[records().length,'সাজানো ক্লাস রেকর্ড','▤'],[entries.length,'সংগ্রহ করা পোস্ট','▧'],[verifiedVideoCount(),'প্লেব্যাক যাচাই করা ভিডিও','▷'],[entries.filter(e=>e.noteText).length,'সাইটে পড়ার পূর্ণ নোট','≡']])append(stats,append(node('div',null,'stat'),node('span',symbol,'stat-symbol'),node('span',label),node('strong',bn(value))));$('page').append(stats);
 const layout=node('div',null,'dashboard-grid');const left=node('section');left.append(sectionHeading('ধারাবাহিকভাবে শেখা শুরু করুন','#classes','সব ক্লাস ↗'));const rows=node('div',null,'class-list');records().slice(0,4).forEach(e=>rows.append(classRow(e)));left.append(rows);const right=node('section');right.append(sectionHeading('সাপ্তাহিক সময়সূচি','#schedule','সময়সূচি ↗'));right.append(append(node('div',null,'panel'),weekly(true),node('p','সময় অঞ্চল মূল পোস্টে উল্লেখ নেই। বিশেষ নোটিশ অনুযায়ী সময় বদলাতে পারে।','muted')));append(layout,left,right);$('page').append(layout,adPlacement('middle'));
 $('page').append(sectionHeading('বিষয় অনুযায়ী ঘুরে দেখুন','#resources','সব রিসোর্স ↗'));const topics=node('div',null,'topic-grid');const featured=['Orientation','SQL Injection','OSINT','XSS','WAF','Burp Suite','File Upload','Linux & Scripting'];for(const [i,t]of featured.entries()){const count=entries.filter(e=>e.topic===t||(e.relatedTopics||[]).includes(t)).length;const c=internal('#resources?topic='+encodeURIComponent(t),null,'topic-card');append(c,node('span',['Δ','SQL','◎','</>','▥','⌘','↑','$_'][i],'topic-symbol'),node('h3',t),node('p',bn(count)+'টি পোস্ট ও রিসোর্স'));topics.append(c);}$('page').append(topics,strip('সাইটের প্রতিটি ক্লাসে ভিডিও, নোট, ডকুমেন্ট ও টুলসের জায়গা প্রস্তুত। যেগুলো বাকি আছে, সেগুলো পরবর্তী ধাপে যুক্ত হবে। অনিশ্চিত তারিখ আলাদাভাবে দেখানো আছে।'));
 $('page').append(adPlacement('footer'));
}
function toolDownloads(pool){
 const files=pool.flatMap(e=>(e.preservedFiles||[]).filter(f=>f.kind==='tool').map(f=>({e,f})));
 const official=pool.filter(e=>e.downloadLinks?.length);
 if(!files.length&&!official.length)return;
 $('page').append(sectionHeading('টুল ফাইল ও অফিসিয়াল ডাউনলোড'),node('p','সংরক্ষিত ZIP/RAR এবং অফিসিয়াল software downloads নিচে আছে। যে বাটন download page খোলে, সেখানে নিজের OS অনুযায়ী installer বাছুন।','muted'));
 if(archive.toolsAudit)$('page').append(strip(archive.toolsAudit.method));
 const grid=node('div',null,'resource-grid tool-downloads');
 for(const {e,f} of files){
  const card=node('article',null,'panel tool-download-card'),size=f.bytes>=1e9?(f.bytes/1e9).toFixed(2)+' GB':(f.bytes/1e6).toFixed(1)+' MB';
  append(card,node('span',e.topic,'eyebrow'),node('h3',f.name),node('p',size+' · সংরক্ষিত কোর্স ফাইল','muted'));
  const password=e.text.match(/(?:password|পাসওয়ার্ড|পাসওয়ার্ড)\s*[:ঃ]\s*([^\s]+)/i);
  if(password)card.append(node('p','ফাইল খোলার পাসওয়ার্ড: '+password[1],'tool-password'));
  const match=f.url.match(/\/file\/d\/([^/]+)/),actions=node('div',null,'hero-actions');
  append(actions,external(match?'https://drive.usercontent.google.com/download?id='+encodeURIComponent(match[1])+'&export=download':f.url,'ডাউনলোড ↓','button primary'),external(f.url,'ফাইল দেখুন ↗','button'),internal(resourceHash(e),'সেটআপ ও নির্দেশনা','button'));
  card.append(actions);grid.append(card);
 }
 for(const e of official){const card=node('article',null,'panel tool-download-card');append(card,node('span',e.topic,'eyebrow'),node('h3',title(e)),node('p','অফিসিয়াল উৎস · নিজস্ব mirror নয়','muted'));const actions=node('div',null,'hero-actions');for(const d of e.downloadLinks)actions.append(external(d.url,d.label,'button primary'));actions.append(internal(resourceHash(e),'সেটআপ ও নির্দেশনা','button'));card.append(actions);grid.append(card);}
 $('page').append(grid,sectionHeading('সেটআপ নির্দেশনা ও পোস্ট'));
}
function collection(view,params){const isClass=view==='classes',isTool=view==='tools',isNotice=view==='notices';const pool=isClass?records():entries.filter(e=>isTool?isToolResource(e):isNotice?['notices','information'].includes(e.category):true);heading(isClass?'COURSE CURRICULUM':isTool?'YOUR LEARNING TOOLKIT':isNotice?'BATCH UPDATES':'RESOURCE LIBRARY',pageNames[view],isClass?'রেকর্ডের সিরিয়াল ধরে ক্লাস সাজানো আছে। একটি ক্লাস খুললে তার ভিডিও ও সংশ্লিষ্ট রিসোর্সের জায়গাগুলো দেখবেন।':isTool?'টুলসের তথ্য, সেটআপ নির্দেশনা ও রিসোর্স লিংক। প্রয়োজনীয় নতুন টুল পরে একই জায়গায় যুক্ত করা যাবে।':isNotice?'ব্যাচের ঘোষণা, ক্লাসের নির্দেশনা ও গুরুত্বপূর্ণ তথ্য এক জায়গায়।':'ভিডিও, নোট, ডকুমেন্ট, টুলস ও তথ্য বিষয় অনুযায়ী খুঁজে নিন।',bn(pool.length)+'টি '+(isClass?'ক্লাস':'পোস্ট'));if(isTool)toolDownloads(pool);
 const bar=node('div',null,'filter-bar');const q=node('input');q.type='search';q.placeholder='ক্লাস, টপিক বা রিসোর্স খুঁজুন…';q.setAttribute('aria-label','খুঁজুন');const search=append(node('label',null,'search-box'),node('span','⌕'),q);const topic=node('select');topic.setAttribute('aria-label','টপিক বাছাই');topic.append(new Option('সব টপিক',''));for(const t of [...new Set(pool.flatMap(e=>[e.topic,...(e.relatedTopics||[])]).filter(Boolean))].sort())topic.append(new Option(t,t));topic.value=params.get('topic')||'';const month=node('select');month.setAttribute('aria-label','মাস বাছাই');month.append(new Option('সব মাস',''));for(const m of [...new Set(pool.map(e=>e.date?.slice(0,7)).filter(Boolean))].sort())month.append(new Option(new Intl.DateTimeFormat('bn-BD',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T00:00:00Z')),m));const reset=button('ফিল্টার মুছুন',()=>{q.value='';topic.value='';month.value='';filterCategory='';tabs?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.category===''));draw();},'filter-reset');append(bar,search,topic,month,reset);$('page').append(bar);
 let tabs=null;if(!isClass&&!isTool&&!isNotice){tabs=node('div',null,'resource-tabs');for(const [key,label]of [['','সব'],...Object.entries(labels)]){const b=button(label,()=>{filterCategory=key;tabs.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});draw();});b.dataset.category=key;b.className=key===''?'active':'';b.setAttribute('aria-pressed',String(key===''));tabs.append(b);}$('page').append(tabs);}filterCategory='';const count=node('p',null,'filter-count'),list=node('div',null,isClass?'class-list':'resource-grid');$('page').append(count,list);
 function draw(){const query=q.value.trim().toLocaleLowerCase();const result=pool.filter(e=>(!filterCategory||e.category===filterCategory)&&(!topic.value||e.topic===topic.value||(e.relatedTopics||[]).includes(topic.value))&&(!month.value||(e.date||'').startsWith(month.value))&&(!query||[e.title,e.topicTitle,e.text,e.noteText,e.author,e.topic,e.date].join(' ').toLocaleLowerCase().includes(query)));if(!isClass)result.sort((a,b)=>!a.date&&!b.date?a.collectionIndex-b.collectionIndex:!a.date?1:!b.date?-1:a.date.localeCompare(b.date)||a.collectionIndex-b.collectionIndex);count.textContent=bn(result.length)+'টি ফলাফল'+(isClass?' · রেকর্ডের সিরিয়াল অনুযায়ী':' · তারিখ অনুযায়ী');list.replaceChildren();result.forEach(e=>list.append(isClass?classRow(e):card(e)));if(!result.length)list.append(empty('কোনো রিসোর্স পাওয়া যায়নি','অন্য টপিক বা মাস বেছে নিন, অথবা অনুসন্ধানটি মুছে আবার দেখুন।'));}
 q.oninput=draw;topic.onchange=draw;month.onchange=draw;draw();
}
function relatedResources(e){return entries.filter(x=>x.id!==e.id&&((e.relatedResourceIds||[]).includes(x.id)||x.relatedRecordingId===e.id||(x.relatedRecordingIds||[]).includes(e.id)||(x.classDate&&x.classDate===e.date)||(e.date&&x.date===e.date&&['documents','tools','information'].includes(x.category))));}
function linkLabel(url){try{const u=new URL(url,location.origin);return u.hostname==='docs.google.com'?'Google Docs · ক্লাস ডকুমেন্ট':u.hostname==='drive.google.com'?'Google Drive · সোর্স ফাইল':u.hostname.includes('youtu')?'YouTube ভিডিও':u.hostname+' ↗';}catch{return 'রিসোর্স লিংক';}}
function resourceLinks(e,parent,source=true){const links=node('div',null,'resource-links');if(e.documentUrl)links.append(external(e.documentUrl,'সংরক্ষিত ফাইল ডাউনলোড ↓'));for(const f of e.preservedFiles||[])links.append(external(f.url,'সংরক্ষিত কপি · '+f.name+' ↓'));if(e.backupDocumentUrl)links.append(external(e.backupDocumentUrl,'Drive-এ অতিরিক্ত কপি ↗'));for(const url of new Set(e.links||[]))if(url!==e.documentUrl)links.append(external(url,linkLabel(url)));for(const d of e.downloadLinks||[])links.append(external(d.url,d.label));if(e.category!=='recordings')for(const id of new Set([e.relatedRecordingId,...(e.relatedRecordingIds||[])].filter(Boolean))){const record=entries.find(x=>x.id===id);if(record)links.append(internal('#class/'+id,'সংশ্লিষ্ট ক্লাস '+bn(record.recordingSerial)+' ↗','resource-link'));}if(source&&e.source)links.append(external(e.source,'মূল Facebook পোস্ট ↗'));if(links.childElementCount)parent.append(links);if(e.preservedFiles?.length){const info=node('details',null,'file-integrity');info.append(node('summary','সংরক্ষিত ফাইলের তথ্য'));for(const f of e.preservedFiles){const item=node('div');append(item,node('strong',f.name),node('p',new Intl.NumberFormat('bn-BD').format(f.bytes)+' bytes','muted'),node('code','SHA256: '+f.sha256));info.append(item);}parent.append(info);}if(e.archivedVideos?.length){const info=node('details',null,'file-integrity');info.append(node('summary','আর্কাইভের '+bn(e.archivedVideos.length)+'টি সহায়ক ভিডিও'));info.append(node('p','ভিডিওগুলো সংরক্ষিত RAR ফাইলে আছে। উপরের কপি ডাউনলোড করে কোর্স পোস্টে দেওয়া পাসওয়ার্ড দিয়ে খোলা যায়।'));const list=node('ol');e.archivedVideos.forEach(name=>list.append(node('li',name.replaceAll('\\',' / '))));info.append(list);parent.append(info);}}
function textWithLinks(text){const p=node('div',null,'body-text');let cursor=0;for(const m of text.matchAll(/https?:\/\/[^\s<>"()]+/g)){p.append(document.createTextNode(text.slice(cursor,m.index)),external(m[0],m[0],''));cursor=m.index+m[0].length;}p.append(document.createTextNode(text.slice(cursor)));return p;}
function notesView(e,parent){const items=[e,...relatedResources(e)].filter(isNoteResource);if(!items.length){parent.append(slot('ক্লাস নোট পরে যোগ হবে','এই ক্লাসের লিখিত নোট, সারাংশ ও গুরুত্বপূর্ণ বিষয় রাখার জায়গা প্রস্তুত।','note',e.id));return;}for(const n of items){const s=append(node('section',null,'note-content'),node('h3',title(n)));if(n.noteText)s.append(textWithLinks(n.noteText));else if(!n.documentUrl&&n.text){s.append(textWithLinks(n.text));resourceLinks(n,s);}if(n.documentUrl){if(safeDocumentURL(n.documentUrl)){const f=node('iframe',null,'document-player');f.src=safeDocumentURL(n.documentUrl);f.title=title(n);f.loading='lazy';s.append(f);}s.append(external(n.documentUrl,'সংরক্ষিত নোট ডাউনলোড ↓'));}if(n.noteUrl&&!n.documentUrl)s.append(external(n.noteUrl,'পূর্ণ নোট ডাউনলোড করুন ↗'));parent.append(s);}}
function detail(e,params){const isClass=e.category==='recordings';$('page').append(internal(isClass?'#classes':'#resources','← '+(isClass?'সব ক্লাসে ফিরুন':'লাইব্রেরিতে ফিরুন'),'back-link'));heading(isClass?'CLASS '+String(e.recordingSerial).padStart(2,'0'):(labels[e.category]||'RESOURCE'),title(e),isClass?(e.topicVerification||'ক্লাসের টপিক ও পূর্ণ রিসোর্স তালিকা পরবর্তী ধাপে যাচাই করে যোগ হবে।'):null);
 const layout=node('div',null,'class-detail-layout'),main=node('section'),aside=node('aside',null,'panel detail-sidebar');const playable=entries.find(x=>x.id===e.archivedRecordingId&&x.category==='recordings')||e;const youtube=playable.youtubeId||(playable.videoStatus==='uploaded-processing'?playable.pendingYoutubeId:null);if(dailymotionPlayer(playable,main)){}else if(youtube&&/^[\w-]{11}$/.test(youtube)){if(!playable.youtubeId)main.append(strip('YouTube processing চলছে। প্রস্তুত হলে এই প্লেয়ারেই ভিডিও দেখা যাবে।'));const f=node('iframe',null,'player');f.src='https://www.youtube-nocookie.com/embed/'+youtube;f.title=title(e);f.allow='autoplay; encrypted-media; fullscreen; picture-in-picture';f.referrerPolicy='strict-origin-when-cross-origin';f.allowFullscreen=true;main.append(f);}else if(isClass||e.category==='classes'){const box=node('div',null,'player-placeholder');append(box,node('span','▷','play-circle'),node('h3',status(e).text),node('p',e.videoUploadMessage|| (e.videoStatus==='upload-blocked-daily-limit'?'YouTube-এর দৈনিক আপলোড সীমায় আছে। সংরক্ষিত Drive কপি নিচের রিসোর্সে পাওয়া যাবে।':e.videoStatus==='uploading'?'শুরু করা আপলোডের কাজ সংরক্ষিত আছে। যাচাই করা ভিডিও এখানে যুক্ত হলে সাইটের ভেতরেই দেখা যাবে।':'এই ক্লাসের ভিডিও রাখার জায়গা প্রস্তুত। ভিডিও লিংক যোগ হলে এখানেই প্লে হবে।')));main.append(box);}
 const meta=node('div',null,'detail-meta');for(const [label,value]of [[isClass?'ক্লাসের তারিখ':e.classDate?'সংশ্লিষ্ট ক্লাসের তারিখ':'পোস্টের তারিখ',classDateLabel(e)],[e.classStartTime?'পোস্টে দেওয়া সময়':'নিয়মিত ক্লাসের সময়',e.classStartTime||e.scheduledTime||'সময় যাচাই বাকি'],['ভিডিওর দৈর্ঘ্য',e.duration||'পরে যোগ হবে']])append(meta,append(node('div'),node('span',label),node('strong',value)));main.append(meta);const tabs=node('div',null,'detail-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','ক্লাসের রিসোর্স');const tabContent=node('section',null,'detail-tab-content');tabContent.id='detail-tab-content';tabContent.setAttribute('role','tabpanel');let selected=params.get('tab')||'overview';if(!['overview','notes','documents','tools'].includes(selected))selected='overview';
 function drawTab(name){selected=name;tabs.querySelectorAll('button').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active)tabContent.setAttribute('aria-labelledby',b.id);});tabContent.replaceChildren();const related=relatedResources(e);
  if(name==='overview'){tabContent.append(node('h3','ক্লাসের তথ্য'));if(e.topic)tabContent.append(node('p','বিষয়: '+(e.topicTitle||e.topic),'muted'));if(isClass)tabContent.append(node('p','রেকর্ড #'+bn(e.recordingSerial)+' · '+classDateLabel(e)+'. এই ক্লাসের ভিডিও ও সংশ্লিষ্ট রিসোর্স নিচের জায়গাগুলোতে পাওয়া যাবে।','muted'));else if(e.text)tabContent.append(textWithLinks(e.text));if(e.classDateVerification)tabContent.append(strip(e.classDateVerification));if(e.scheduledTime&&!e.classStartTime)tabContent.append(strip('উপরের সময় সাপ্তাহিক শিডিউল অনুযায়ী। এই রেকর্ডের প্রকৃত শুরুর সময় যাচাই বাকি।'));const slots=node('div',null,'slot-grid');append(slots,slot('ক্লাস ভিডিও',(youtube||dailymotionClips(playable).length)?'সাইটের প্লেয়ারে ভিডিও যুক্ত আছে।':'ভিডিওর জায়গা প্রস্তুত; যাচাই করা ভিডিও পরে যোগ হবে।','video',e.id,!!(youtube||dailymotionClips(playable).length)),slot('ক্লাস নোট',[e,...related].some(isNoteResource)?'সংরক্ষিত নোট “নোট” ট্যাবে পড়া যাবে।':'ক্লাসের সারাংশ ও লিখিত নোট পরে যোগ হবে।','note',e.id,[e,...related].some(isNoteResource)),slot('ডকুমেন্ট',related.some(x=>hasResourceKind(x,'documents'))?'সংশ্লিষ্ট ডকুমেন্ট “ডকুমেন্ট” ট্যাবে আছে।':'PDF, স্লাইড ও প্রয়োজনীয় ফাইল পরে যোগ হবে।','document',e.id,related.some(x=>hasResourceKind(x,'documents'))),slot('টুলস ও সেটআপ',related.some(isToolResource)?'সংশ্লিষ্ট টুলস “টুলস” ট্যাবে আছে।':'প্রয়োজনীয় টুলস ও সেটআপ নির্দেশনা পরে যোগ হবে।','tool',e.id,related.some(isToolResource)));tabContent.append(slots);if(isClass){const info=related.filter(x=>['information','classes'].includes(x.category));for(const x of info){const section=node('section',null,'note-content');section.append(node('h3',title(x)));if(x.text)section.append(textWithLinks(x.text));resourceLinks(x,section);tabContent.append(section);}}resourceLinks(e,tabContent);if(e.classDate)tabContent.append(node('p','সংশ্লিষ্ট ক্লাসের তারিখ: '+date(e.classDate),'muted'));}
  if(name==='notes')notesView(e,tabContent);
  if(name==='documents'||name==='tools'){const category=name==='documents'?'documents':'tools';const relevant=related.filter(x=>hasResourceKind(x,category));if(hasResourceKind(e,category))relevant.unshift(e);if(name==='tools'&&isClass){const audit=archive.toolsAudit?.classes.find(x=>x.recordingId===e.id);if(audit)tabContent.append(strip(audit.note));}if(relevant.length){for(const x of relevant){const p=node('section',null,'note-content');p.append(node('h3',title(x)));if(x!==e)p.append(internal(resourceHash(x),'বিস্তারিত দেখুন ↗','text-link'));if(x.text)p.append(textWithLinks(x.text));if(safeDocumentURL(x.documentUrl)){const f=node('iframe',null,'document-player');f.src=safeDocumentURL(x.documentUrl);f.title=title(x);f.loading='lazy';p.append(f);}resourceLinks(x,p);tabContent.append(p);}}else tabContent.append(slot(name==='documents'?'ক্লাস ডকুমেন্ট পরে যোগ হবে':'ক্লাসের টুলস পরে যোগ হবে',name==='documents'?'PDF, স্লাইড, ক্লাস ফাইল ও অন্যান্য ডকুমেন্ট এখানে রাখার জায়গা প্রস্তুত।':'এই ক্লাসের প্রয়োজনীয় টুল, সেটআপ গাইড ও ব্যবহারবিধি এখানে রাখা যাবে।',name==='documents'?'document':'tool',e.id));}
 }
 for(const [key,label]of [['overview','ক্লাসের তথ্য'],['notes','নোট'],['documents','ডকুমেন্ট'],['tools','টুলস']]){const b=button(label,()=>drawTab(key));b.dataset.tab=key;b.id='tab-'+key;b.setAttribute('role','tab');b.setAttribute('aria-controls','detail-tab-content');b.onkeydown=event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const children=[...tabs.children],index=children.indexOf(b);const next=event.key==='Home'?0:event.key==='End'?children.length-1:(index+(event.key==='ArrowRight'?1:-1)+children.length)%children.length;drawTab(children[next].dataset.tab);children[next].focus();}};tabs.append(b);}main.append(tabs,tabContent);drawTab(selected);
 if(isClass){aside.append(node('p','COURSE CONTENT','eyebrow'),node('h3','সব ক্লাস'));const rows=node('div',null,'class-list');records().forEach(x=>{const row=classRow(x,true);if(x.id===e.id){row.classList.add('is-current');row.setAttribute('aria-current','page');}rows.append(row);});aside.append(rows);const sorted=records(),index=sorted.findIndex(x=>x.id===e.id),navigation=node('div',null,'detail-prev-next');if(index>0)navigation.append(internal(resourceHash(sorted[index-1]),'← আগের ক্লাস','button'));if(index<sorted.length-1)navigation.append(internal(resourceHash(sorted[index+1]),'পরের ক্লাস →','button primary'));main.append(navigation);}else{aside.append(node('h3','রিসোর্সের তথ্য'),node('p',labels[e.category]||'রিসোর্স','muted'),node('p',e.author||'Arena B66 Delta','muted'),badge(e));}append(layout,main,aside);$('page').append(layout);
}
function schedule(){heading('CLASS CALENDAR','ক্লাসের সময়সূচি','নিয়মিত ক্লাস ও সাপোর্টের সময় দেখুন। নিচের তালিকায় সংগ্রহ করা রেকর্ডের তারিখ দেখানো আছে।');$('page').append(weekly(),strip(archive.schedule?.timeZoneNote||'পোস্টে সময় অঞ্চল উল্লেখ নেই।'),external(archive.schedule?.source,'অফিশিয়াল সময়সূচির মূল পোস্ট ↗'));$('page').append(sectionHeading('তারিখ অনুযায়ী ক্লাস রেকর্ড'));const month=node('select');month.setAttribute('aria-label','ক্যালেন্ডারের মাস বাছাই');month.append(new Option('সব মাস',''));for(const m of [...new Set(records().map(e=>e.date?.slice(0,7)).filter(Boolean))].sort())month.append(new Option(new Intl.DateTimeFormat('bn-BD',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T00:00:00Z')),m));const bar=node('div',null,'filter-bar');bar.append(month);$('page').append(bar);const grid=node('div',null,'calendar-grid');function draw(){grid.replaceChildren();for(const e of records().filter(e=>!month.value||(e.date||'').startsWith(month.value))){const a=node('article',null,'calendar-item');append(a,node('div',classDateLabel(e,false),'calendar-date'),node('span','রেকর্ড #'+bn(e.recordingSerial),'eyebrow'),node('h3',title(e)),node('p',e.classStartTime?'পোস্টে দেওয়া সময়: '+e.classStartTime:'সাপ্তাহিক সময়: রাত ৯:৩০–১১:৩০ · প্রকৃত সময় যাচাই বাকি'),internal(resourceHash(e),'ক্লাসের বিস্তারিত ↗','text-link'));grid.append(a);}}month.onchange=draw;draw();$('page').append(grid);}
function about(){heading('ABOUT THE ARCHIVE','শেখার জন্য সাজানো একটি জায়গা','Arena Web Security · Batch 66 Delta');const grid=node('div',null,'about-grid');for(const [h,p]of [['ক্লাসের ধারাবাহিকতা','ক্লাস রেকর্ড আলাদা সিরিয়াল অনুযায়ী সাজানো। collectionIndex পোস্ট সংগ্রহের ক্রম; সেটি ক্লাস নম্বর হিসেবে দেখানো হয় না।'],['পরে রিসোর্স যোগ করা যাবে','প্রতিটি ক্লাসে ভিডিও, নোট, ডকুমেন্ট ও টুলসের জায়গা আছে। নতুন যাচাই করা রিসোর্স সংশ্লিষ্ট ক্লাসে যুক্ত করা যাবে।'],['তারিখ ও সময়ের তথ্য','যাচাই না হওয়া পোস্টের তারিখ আলাদাভাবে দেখানো হয়। রেকর্ডের তারিখ ও সাপ্তাহিক শিডিউল দেখানো আছে; প্রকৃত ক্লাসের সময় নিশ্চিত হলে যুক্ত হবে।'],['ভিডিও দেখার ব্যবস্থা','যুক্ত YouTube ও Dailymotion ভিডিও ওয়েবসাইটের ভেতরেই প্লে হবে। বাকি ভিডিওর জন্য প্রস্তুত জায়গা আছে। Facebook সোর্স লিংক দেখতে সদস্যপদ প্রয়োজন হতে পারে।']])grid.append(append(node('article',null,'panel'),node('h3',h),node('p',p)));$('page').append(grid,strip('ওয়েবসাইটের কাঠামো প্রস্তুত। কোর্সের সব রিসোর্স সংগ্রহ ও তারিখ যাচাই এখনো সম্পূর্ণ নয়।'),external('https://github.com/mdnhbn/arena-b66-delta-archive','সাইটের GitHub repository ↗'));}
function route(){if(!archive)return;const raw=location.hash.slice(1)||'overview';const [path,query='']=raw.split('?');const parts=path.split('/');const params=new URLSearchParams(query);let view=parts[0],id=parts[1];if(view.startsWith('entry-')){id=view;view=entries.find(e=>e.id===id)?.category==='recordings'?'class':'resource';}if(!pageNames[view])view='overview';currentPage=view;document.body.classList.toggle('home-banner-layout',view==='overview');document.title=(pageNames[view]||'Delta Archive')+' · Arena B66';$('breadcrumb-current').textContent=pageNames[view];$('page').replaceChildren();document.querySelectorAll('[data-page]').forEach(a=>{const active=a.dataset.page===view||(view==='class'&&a.dataset.page==='classes')||(view==='resource'&&a.dataset.page==='resources');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('sidebar').classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0);if(view==='overview')overview();else if(['classes','resources','tools','notices'].includes(view))collection(view,params);else if(view==='roadmap')roadmap();else if(view==='preservation')preservation();else if(view==='schedule')schedule();else if(view==='about')about();else if(view==='class'||view==='resource'){const e=entries.find(x=>x.id===id);if(e)detail(e,params);else $('page').append(empty('এই রিসোর্সটি পাওয়া যায়নি','লাইব্রেরি থেকে একটি ক্লাস বা রিসোর্স বেছে নিন।','#resources'));}window.dispatchEvent(new Event('delta:page'));}
function closeMenu(){$('sidebar').classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false');$('menu-toggle').setAttribute('aria-label','মেনু খুলুন');}
$('menu-toggle').onclick=()=>{const open=$('sidebar').classList.toggle('open');$('menu-toggle').setAttribute('aria-expanded',String(open));$('menu-toggle').setAttribute('aria-label',open?'মেনু বন্ধ করুন':'মেনু খুলুন');};document.addEventListener('click',e=>{if($('sidebar').classList.contains('open')&&!$('sidebar').contains(e.target)&&!$('menu-toggle').contains(e.target))closeMenu();});$('sidebar').querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});window.addEventListener('hashchange',route);
fetch('data.json').then(r=>{if(!r.ok)throw Error('Data unavailable');return r.json();}).then(data=>{if(!Array.isArray(data.entries))throw Error('Invalid archive');archive=data;entries=data.entries;$('class-count').textContent=bn(records().length);route();}).catch(()=>{$('page').replaceChildren(empty('তথ্য লোড হয়নি','পেজটি আবার খুলুন। সাইটের কাঠামো ও রিসোর্স আলাদাভাবে সংরক্ষিত আছে।'));});

pageNames.roadmap='সিলেবাস ও রোডম্যাপ';pageNames.preservation='সংরক্ষিত আর্কাইভ';
function applyTheme(theme){const light=theme==='light';document.documentElement.dataset.theme=light?'light':'dark';const b=$('theme-toggle');if(b){b.textContent=light?'☾ ডার্ক মোড':'☀ লাইট মোড';b.setAttribute('aria-label',light?'ডার্ক মোড চালু করুন':'লাইট মোড চালু করুন');b.setAttribute('aria-pressed',String(light));}document.querySelector('meta[name="theme-color"]')?.setAttribute('content',light?'#f4faf2':'#0b1519');try{localStorage.setItem('delta-theme',light?'light':'dark');}catch{}}
if($('theme-toggle')){$('theme-toggle').onclick=()=>applyTheme(document.documentElement.dataset.theme==='light'?'dark':'light');applyTheme(document.documentElement.dataset.theme);}
const roadmapStatuses={covered:'ক্লাস পাওয়া গেছে',partial:'আংশিক পাওয়া গেছে',pending:'ক্লাসের প্রমাণ নেই'};
function roadmap(){
 const syllabus=archive.syllabus;
 if(!syllabus){heading('COURSE ROADMAP','সিলেবাস প্রস্তুত হচ্ছে','যাচাই করা সিলেবাস পরে যুক্ত হবে।');return;}
 heading('OFFICIAL SYLLABUS · VERSION 7','সিলেবাস ও ক্লাস — পাশাপাশি','বাঁয়ে অফিসিয়াল PDF-এর বিষয়গুলো, ডানে পাওয়া ক্লাসের তারিখ, ভিডিও ও যাচাইয়ের অবস্থা। সিলেবাসের সপ্তাহ ও বাস্তব ক্লাসের ক্রম আলাদা হতে পারে।');
 const actions=node('div',null,'hero-actions');
 const download=external(syllabus.documentUrl,'মূল সিলেবাস ডাউনলোড ↓','button primary');download.setAttribute('download','arena-course-syllabus-v7.pdf');
 append(actions,download,external(syllabus.documentUrl,'মূল PDF খুলুন ↗','button'),external(syllabus.sourceUrl,'অফিসিয়াল কোর্স পেজ ↗','button'));$('page').append(actions);
 const original=node('details',null,'syllabus-original panel');original.append(node('summary','মূল অফিসিয়াল সিলেবাস দেখুন · ৬ পৃষ্ঠা'));
 const frame=node('iframe',null,'document-player');frame.src=safeDocumentURL(syllabus.documentUrl);frame.title='Arena Web Security অফিসিয়াল সিলেবাস';frame.loading='lazy';
 original.append(frame,node('p','উৎস যাচাই: '+syllabus.verifiedAt+' · Version '+syllabus.version,'muted'));$('page').append(original);
 const stages=syllabus.stages||[],totals=node('section',null,'stat-grid');
 for(const state of ['covered','partial','pending'])totals.append(append(node('article',null,'stat'),node('strong',bn(stages.filter(x=>x.status===state).length)),node('span',roadmapStatuses[state])));
 totals.append(append(node('article',null,'stat'),node('strong',bn(records().length)),node('span','সংরক্ষিত মূল ক্লাস')));
 $('page').append(totals,strip('ক্লাস পাওয়া গেছে মানে সংশ্লিষ্ট বিষয়ের রেকর্ড শনাক্ত হয়েছে; সব উপবিষয়, পরীক্ষা বা কোর্স সম্পূর্ণ হওয়ার নিশ্চয়তা নয়। প্রমাণ নেই মানে ক্লাস হয়নি—এমন সিদ্ধান্ত নয়।'));
 const filters=node('div',null,'resource-tabs'),list=node('div',null,'syllabus-comparison');let chosen='all';
 for(const [key,label]of [['all','সব বিষয়'],['covered','ক্লাস পাওয়া গেছে'],['partial','আংশিক'],['pending','বাকি / যাচাই বাকি']]){const b=button(label,()=>{chosen=key;draw();},'button');b.dataset.status=key;filters.append(b);}
 function draw(){
  filters.querySelectorAll('button').forEach(b=>{b.classList.toggle('primary',b.dataset.status===chosen);b.setAttribute('aria-pressed',String(b.dataset.status===chosen));});list.replaceChildren();
  const columnTitles=node('div',null,'comparison-head');append(columnTitles,node('strong','অফিসিয়াল সিলেবাস'),node('strong','যে ক্লাসগুলো পাওয়া গেছে'));list.append(columnTitles);
  for(const stage of stages.filter(x=>chosen==='all'||x.status===chosen)){
   const row=node('article',null,'comparison-row '+stage.status),left=node('section',null,'syllabus-column'),right=node('section',null,'classes-column');
   append(left,node('span',stage.week+' · অফিসিয়াল সিলেবাস','eyebrow'),node('h2',stage.title));
   const topics=node('ul',null,'syllabus-topics');(stage.officialTopics||[]).forEach(t=>topics.append(node('li',t)));left.append(topics);
   for(const pg of stage.pdfPages||[stage.pdfPage])left.append(external(syllabus.documentUrl+'#page='+pg,'মূল PDF · পৃষ্ঠা '+bn(pg)+' ↗','resource-link'));
   append(right,node('span',roadmapStatuses[stage.status],'badge '+(stage.status==='covered'?'ready':'pending')),node('p',stage.summary,'muted'));
   const links=node('div',null,'roadmap-classes');
   for(const id of stage.classIds||[]){const e=entries.find(e=>e.id===id);if(e){const item=node('div',null,'mapped-class');append(item,internal(resourceHash(e),'ক্লাস '+bn(e.recordingSerial)+' · '+title(e),'button'),append(node('div',null,'mapped-class-meta'),node('span',classDateLabel(e)),badge(e)));links.append(item);}}
   if(links.childElementCount)right.append(links);else right.append(node('p','সংরক্ষিত মূল ক্লাসের তালিকায় এই বিষয়ের নির্দিষ্ট রেকর্ড শনাক্ত হয়নি।','roadmap-remaining'));
   if(stage.remaining)right.append(node('p','আরও যাচাই / বাকি: '+stage.remaining,'roadmap-remaining'));
   append(row,left,right);list.append(row);
  }
 }
 $('page').append(filters,list);draw();
}
function preservation(){heading('PRESERVED LEARNING RESOURCES','Facebook-এর বাইরে আপনার আর্কাইভ','সংরক্ষিত লেখা, নোট ও নিজস্ব ফাইল থাকলে মূল গ্রুপ বন্ধ হলেও সেগুলো পাওয়া যাবে।');const grid=node('div',null,'about-grid');for(const [h,t]of [['পোস্ট ও তথ্য','সংগৃহীত পোস্টের লেখা data.json এবং CATALOG.md-তে আছে। Facebook লিংক শুধু উৎসের পরিচয়; সংরক্ষিত লেখা পড়তে Facebook প্রয়োজন নেই।'],['নোট ও PDF','পূর্ণ নোট GitHub-এর notes ফোল্ডারে আছে। নিজস্ব PDF কপি সাইটের documents ফোল্ডার থেকে পড়া ও ডাউনলোড করা যায়।'],['ভিডিও','যাচাই করা রেকর্ড আপনার YouTube-এ Unlisted অথবা Dailymotion-এ লিংক দিয়ে দেখা যায় এমন Private হিসেবে থাকে এবং সাইটের প্লেয়ারে চলে। আপলোড ও প্লেব্যাক যাচাইয়ের পর ডাউনলোড কপি সরানো হয়।'],['টুল ফাইল','ছোট ও পুনর্বিতরণযোগ্য টুল ফাইল GitHub-এ রাখা যায়। বড় ফাইলের জন্য আপনার Drive/Terabox-এ অতিরিক্ত কপি ভালো। সেটআপ, সংস্করণ, উৎস ও checksum সংরক্ষণ করলে পুনরুদ্ধার সহজ হয়।']])grid.append(append(node('article',null,'panel'),node('h3',h),node('p',t)));$('page').append(grid,strip('কোনো অনলাইন সেবা আজীবন সংরক্ষণের নিশ্চয়তা দেয় না। GitHub, ভিডিও হোস্ট ও আলাদা Drive/Terabox ব্যাকআপ নিয়মিত পরীক্ষা করা উচিত। নিজস্ব কপি যুক্ত হয়নি এমন বাহ্যিক ফাইল এখনো সংরক্ষিত নয়।'));const actions=node('div',null,'hero-actions');append(actions,external('/data.json','তথ্যের JSON কপি ↓','button primary'),external('/CATALOG.md','পোস্টের লিখিত ক্যাটালগ ↓','button'),external('https://github.com/mdnhbn/arena-b66-delta-archive','GitHub-এর ফাইল ↗','button'));$('page').append(actions,sectionHeading('সংরক্ষিত নোট, ফাইল ও প্রস্তুত ভিডিও'));const list=node('div',null,'resource-grid');entries.filter(e=>e.noteText||e.documentUrl||e.youtubeId||dailymotionClips(e).length||e.preservedFiles?.length).forEach(e=>list.append(card(e)));$('page').append(list);}
