'use strict';
const $=id=>document.getElementById(id);
const labels={recordings:'ক্লাস রেকর্ডিং',classes:'ক্লাস ও ভিডিও',documents:'নোট ও ডকুমেন্ট',tools:'টুলস ও সেটআপ',information:'তথ্য ও নির্দেশনা',notices:'নোটিশ'};
const pageNames={overview:'ড্যাশবোর্ড',classes:'সব ক্লাস',resources:'রিসোর্স লাইব্রেরি',tools:'টুলস ও সেটআপ',schedule:'সময়সূচি',notices:'নোটিশ ও তথ্য',manage:'রিসোর্সের খসড়া',about:'আর্কাইভ সম্পর্কে',class:'ক্লাসের বিস্তারিত',resource:'রিসোর্সের বিস্তারিত'};
let archive,entries=[],drafts=[],filterCategory='',currentPage='overview',toastTimer;
const bn=n=>new Intl.NumberFormat('bn-BD').format(n);
function date(d,year=true){if(!d||!/^\d{4}-\d{2}-\d{2}$/.test(d))return 'তারিখ যাচাই বাকি';const value=new Date(d+'T00:00:00Z');return Number.isFinite(value.getTime())?new Intl.DateTimeFormat('bn-BD',{day:'numeric',month:'long',...(year?{year:'numeric'}:{}),timeZone:'UTC'}).format(value):'তারিখ যাচাই বাকি';}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined&&text!==null)e.textContent=text;if(cls)e.className=cls;return e;}
function append(parent,...children){parent.append(...children.filter(Boolean));return parent;}
function internal(href,text,cls){const a=node('a',text,cls);a.href=href;return a;}
function safeURL(value){try{const u=new URL(value,location.origin);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function external(url,text,cls='resource-link'){const u=safeURL(url);if(!u)return node('span','লিংক যোগ করার অপেক্ষায়','muted');const a=node('a',text,cls);a.href=u;a.target='_blank';a.rel='noopener noreferrer';return a;}
function button(text,handler,cls='button'){const b=node('button',text,cls);b.type='button';b.onclick=handler;return b;}
function records(){return entries.filter(e=>e.category==='recordings').sort((a,b)=>(a.recordingSerial||999)-(b.recordingSerial||999));}
function title(e){return e.topicTitle||e.title;}
function resourceHash(e){return '#'+(e.category==='recordings'?'class/':'resource/')+e.id;}
function status(e){if(e.youtubeId)return {text:'ভিডিও প্রস্তুত',cls:'ready'};if(e.videoStatus==='uploading'||e.videoStatus==='uploaded-processing')return {text:'ভিডিও প্রস্তুত হচ্ছে',cls:'pending'};if(e.category==='recordings'||(e.videoStatus||'').startsWith('upload-'))return {text:'ভিডিও পরে যোগ হবে',cls:'pending'};return {text:e.noteText?'নোট পড়া যাবে':'রিসোর্স',cls:''};}
function badge(e){const s=status(e);return node('span',s.text,'badge '+s.cls);}
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').hidden=true;},4500);}
function heading(label,h1,description,count){const div=node('div',null,'page-heading');const copy=node('div');append(copy,node('div',label,'eyebrow'),node('h1',h1),description?node('p',description):null);div.append(copy);if(count!==undefined)div.append(node('span',count,'count-pill'));$('page').append(div);}
function sectionHeading(text,href,linkText){const s=node('div',null,'section-heading');s.append(node('h2',text));if(href)s.append(internal(href,linkText||'সব দেখুন ↗','text-link'));return s;}
function strip(text){return append(node('aside',null,'notice-strip'),node('span','◈'),node('p',text));}
function slot(label,description,kind,id,filled=false){const box=node('section',null,'resource-slot'+(filled?' filled':''));const top=node('div',null,'slot-title');append(top,node('span',({video:'▷',note:'≡',document:'▧',tool:'⌘'})[kind]||'＋','slot-icon'),node('h3',label));append(box,top,node('p',description));if(!filled)box.append(internal('#manage?class='+encodeURIComponent(id||'')+'&kind='+kind,'＋ এই জায়গায় রিসোর্সের খসড়া যোগ করুন'));return box;}
function empty(label,text,href){const e=append(node('div',null,'empty-state'),node('span','▧','empty-icon'),node('h3',label),node('p',text));if(href)e.append(internal(href,'রিসোর্স যোগ করার অপশন ↗','button'));return e;}
function classRow(e,compact=false){const a=internal(resourceHash(e),null,'class-row');const main=node('div',null,'class-main');append(main,node('h3',title(e)),append(node('div',null,'class-meta'),node('span',date(e.classDate||e.date,false)),!compact&&e.duration?node('span',e.duration):null,!compact&&e.topic?node('span',e.topic):null));append(a,node('span',String(e.recordingSerial||'').padStart(2,'0'),'class-number'),main,!compact?badge(e):null,node('span','↗','row-arrow'));return a;}
function card(e){const c=node('article',null,'resource-card');append(c,node('span',labels[e.category]||'রিসোর্স','badge'),node('h3',title(e)),node('p',(e.text||'রিসোর্সের বিস্তারিত তথ্য পরে যোগ হবে।').replace(/\s+/g,' ').slice(0,130)+((e.text||'').length>130?'…':'')));append(c,append(node('div',null,'card-foot'),node('span',date(e.date,false)),internal(resourceHash(e),'বিস্তারিত ↗','text-link')));return c;}
function weekly(compact=false){const s=node('div',null,compact?'':'schedule-large');for(const [short,day,time,info]of [['শুক্র','শুক্রবার','রাত ৯:৩০–১১:৩০','নিয়মিত ক্লাস'],['রবি','রবিবার','রাত ৯:৩০–১১:৩০','নিয়মিত ক্লাস'],['মঙ্গল','মঙ্গলবার','সন্ধ্যা ৭টা–রাত ১টা','প্র্যাকটিস ও সাপোর্ট']]){const a=node(compact?'div':'article',null,compact?'schedule-day':'');if(compact){append(a,node('span',short,'day-block'),append(node('div'),node('strong',day),node('p',time+' · '+info)));}else append(a,node('span',info,'eyebrow'),node('h3',day),node('strong',time),node('p','অফিশিয়াল ব্যাচের সাপ্তাহিক সময়সূচি'));s.append(a);}return s;}
function overview(){const hero=node('section',null,'hero');const copy=node('div',null,'hero-copy');const h=node('h1');append(h,document.createTextNode('একটি ব্যাচ।'),node('br'),node('span','শেখার সবকিছু এক জায়গায়।'));append(copy,node('div','YOUR WEB SECURITY JOURNEY','eyebrow'),h,node('p','শুরু থেকে ধারাবাহিকভাবে ক্লাস দেখুন। প্রতিটি ক্লাসের সঙ্গে নোট, ডকুমেন্ট ও প্রয়োজনীয় টুলস খুঁজে নিন।'),append(node('div',null,'hero-actions'),internal('#classes','ক্লাস শুরু করুন →','button primary'),internal('#resources','রিসোর্স লাইব্রেরি','button ghost')));const art=node('div',null,'hero-art');art.setAttribute('aria-hidden','true');append(art,node('div',null,'orbit'),node('span','Δ','delta-glyph'),node('span','WEB SECURITY','floating-chip chip-one'),node('span','< learn / practice >','floating-chip chip-two'),node('span','BATCH 66 · DELTA','floating-chip chip-three'));append(hero,copy,art);$('page').append(hero);
 const stats=node('section',null,'stat-grid');stats.setAttribute('aria-label','আর্কাইভের পরিসংখ্যান');for(const [value,label,symbol]of [[records().length,'সাজানো ক্লাস রেকর্ড','▤'],[entries.length,'সংগ্রহ করা পোস্ট','▧'],[entries.filter(e=>e.youtubeId).length,'YouTube ভিডিও প্রস্তুত','▷'],[entries.filter(e=>e.noteText).length,'সাইটে পড়ার পূর্ণ নোট','≡']])append(stats,append(node('div',null,'stat'),node('span',symbol,'stat-symbol'),node('span',label),node('strong',bn(value))));$('page').append(stats);
 const layout=node('div',null,'dashboard-grid');const left=node('section');left.append(sectionHeading('ধারাবাহিকভাবে শেখা শুরু করুন','#classes','সব ক্লাস ↗'));const rows=node('div',null,'class-list');records().slice(0,4).forEach(e=>rows.append(classRow(e)));left.append(rows);const right=node('section');right.append(sectionHeading('সাপ্তাহিক সময়সূচি','#schedule','সময়সূচি ↗'));right.append(append(node('div',null,'panel'),weekly(true),node('p','সময় অঞ্চল মূল পোস্টে উল্লেখ নেই। বিশেষ নোটিশ অনুযায়ী সময় বদলাতে পারে।','muted')));append(layout,left,right);$('page').append(layout);
 $('page').append(sectionHeading('বিষয় অনুযায়ী ঘুরে দেখুন','#resources','সব রিসোর্স ↗'));const topics=node('div',null,'topic-grid');const featured=['Orientation','SQL Injection','OSINT','XSS','WAF','Burp Suite','File Upload','Linux & Scripting'];for(const [i,t]of featured.entries()){const count=entries.filter(e=>e.topic===t||(e.relatedTopics||[]).includes(t)).length;const c=internal('#resources?topic='+encodeURIComponent(t),null,'topic-card');append(c,node('span',['Δ','SQL','◎','</>','▥','⌘','↑','$_'][i],'topic-symbol'),node('h3',t),node('p',bn(count)+'টি পোস্ট ও রিসোর্স'));topics.append(c);}$('page').append(topics,strip('সাইটের প্রতিটি ক্লাসে ভিডিও, নোট, ডকুমেন্ট ও টুলসের জায়গা প্রস্তুত। যেগুলো বাকি আছে, সেগুলো পরবর্তী ধাপে যুক্ত হবে। অনিশ্চিত তারিখ আলাদাভাবে দেখানো আছে।'));
}
function collection(view,params){const isClass=view==='classes',isTool=view==='tools',isNotice=view==='notices';const pool=isClass?records():entries.filter(e=>isTool?e.category==='tools':isNotice?['notices','information'].includes(e.category):true);heading(isClass?'COURSE CURRICULUM':isTool?'YOUR LEARNING TOOLKIT':isNotice?'BATCH UPDATES':'RESOURCE LIBRARY',pageNames[view],isClass?'রেকর্ডের সিরিয়াল ধরে ক্লাস সাজানো আছে। একটি ক্লাস খুললে তার ভিডিও ও সংশ্লিষ্ট রিসোর্সের জায়গাগুলো দেখবেন।':isTool?'টুলসের তথ্য, সেটআপ নির্দেশনা ও রিসোর্স লিংক। প্রয়োজনীয় নতুন টুল পরে একই জায়গায় যুক্ত করা যাবে।':isNotice?'ব্যাচের ঘোষণা, ক্লাসের নির্দেশনা ও গুরুত্বপূর্ণ তথ্য এক জায়গায়।':'ভিডিও, নোট, ডকুমেন্ট, টুলস ও তথ্য বিষয় অনুযায়ী খুঁজে নিন।',bn(pool.length)+'টি '+(isClass?'ক্লাস':'পোস্ট'));
 const bar=node('div',null,'filter-bar');const q=node('input');q.type='search';q.placeholder='ক্লাস, টপিক বা রিসোর্স খুঁজুন…';q.setAttribute('aria-label','খুঁজুন');const search=append(node('label',null,'search-box'),node('span','⌕'),q);const topic=node('select');topic.setAttribute('aria-label','টপিক বাছাই');topic.append(new Option('সব টপিক',''));for(const t of [...new Set(pool.flatMap(e=>[e.topic,...(e.relatedTopics||[])]).filter(Boolean))].sort())topic.append(new Option(t,t));topic.value=params.get('topic')||'';const month=node('select');month.setAttribute('aria-label','মাস বাছাই');month.append(new Option('সব মাস',''));for(const m of [...new Set(pool.map(e=>e.date?.slice(0,7)).filter(Boolean))].sort())month.append(new Option(new Intl.DateTimeFormat('bn-BD',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T00:00:00Z')),m));const reset=button('ফিল্টার মুছুন',()=>{q.value='';topic.value='';month.value='';filterCategory='';tabs?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.category===''));draw();},'filter-reset');append(bar,search,topic,month,reset);$('page').append(bar);
 let tabs=null;if(!isClass&&!isTool&&!isNotice){tabs=node('div',null,'resource-tabs');for(const [key,label]of [['','সব'],...Object.entries(labels)]){const b=button(label,()=>{filterCategory=key;tabs.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});draw();});b.dataset.category=key;b.className=key===''?'active':'';b.setAttribute('aria-pressed',String(key===''));tabs.append(b);}$('page').append(tabs);}filterCategory='';const count=node('p',null,'filter-count'),list=node('div',null,isClass?'class-list':'resource-grid');$('page').append(count,list);
 function draw(){const query=q.value.trim().toLocaleLowerCase();const result=pool.filter(e=>(!filterCategory||e.category===filterCategory)&&(!topic.value||e.topic===topic.value||(e.relatedTopics||[]).includes(topic.value))&&(!month.value||(e.date||'').startsWith(month.value))&&(!query||[e.title,e.topicTitle,e.text,e.noteText,e.author,e.topic,e.date].join(' ').toLocaleLowerCase().includes(query)));if(!isClass)result.sort((a,b)=>!a.date&&!b.date?a.collectionIndex-b.collectionIndex:!a.date?1:!b.date?-1:a.date.localeCompare(b.date)||a.collectionIndex-b.collectionIndex);count.textContent=bn(result.length)+'টি ফলাফল'+(isClass?' · রেকর্ডের সিরিয়াল অনুযায়ী':' · তারিখ অনুযায়ী');list.replaceChildren();result.forEach(e=>list.append(isClass?classRow(e):card(e)));if(!result.length)list.append(empty('কোনো রিসোর্স পাওয়া যায়নি','অন্য টপিক বা মাস বেছে নিন, অথবা অনুসন্ধানটি মুছে আবার দেখুন।'));}
 q.oninput=draw;topic.onchange=draw;month.onchange=draw;draw();if(isTool)$('page').append(slot('নতুন টুল ও সেটআপ','পরবর্তী সময়ে টুলের নাম, ব্যবহার ও সেটআপ লিংক এখানে যোগ করা যাবে।','tool',''));
}
function relatedResources(e){return entries.filter(x=>x.id!==e.id&&((e.relatedResourceIds||[]).includes(x.id)||x.relatedRecordingId===e.id||(x.classDate&&x.classDate===e.date)||(e.date&&x.date===e.date&&['documents','tools','information'].includes(x.category))));}
function linkLabel(url){try{const u=new URL(url,location.origin);return u.hostname==='docs.google.com'?'Google Docs · ক্লাস ডকুমেন্ট':u.hostname==='drive.google.com'?'Google Drive · সোর্স ফাইল':u.hostname.includes('youtu')?'YouTube ভিডিও':u.hostname+' ↗';}catch{return 'রিসোর্স লিংক';}}
function resourceLinks(e,parent,source=true){const links=node('div',null,'resource-links');for(const url of e.links||[])links.append(external(url,linkLabel(url)));if(source&&e.source)links.append(external(e.source,'মূল Facebook পোস্ট ↗'));if(links.childElementCount)parent.append(links);}
function textWithLinks(text){const p=node('div',null,'body-text');let cursor=0;for(const m of text.matchAll(/https?:\/\/[^\s<>"()]+/g)){p.append(document.createTextNode(text.slice(cursor,m.index)),external(m[0],m[0],''));cursor=m.index+m[0].length;}p.append(document.createTextNode(text.slice(cursor)));return p;}
function notesView(e,parent){const items=[e,...relatedResources(e)].filter(x=>x.noteText);if(!items.length){parent.append(slot('ক্লাস নোট পরে যোগ হবে','এই ক্লাসের লিখিত নোট, সারাংশ ও গুরুত্বপূর্ণ বিষয় রাখার জায়গা প্রস্তুত।','note',e.id));return;}for(const n of items){const s=append(node('section',null,'note-content'),node('h3',title(n)),textWithLinks(n.noteText));if(n.noteUrl)s.append(external(n.noteUrl,'পূর্ণ নোট ডাউনলোড করুন ↗'));parent.append(s);}}
function detail(e,params){const isClass=e.category==='recordings';$('page').append(internal(isClass?'#classes':'#resources','← '+(isClass?'সব ক্লাসে ফিরুন':'লাইব্রেরিতে ফিরুন'),'back-link'));heading(isClass?'CLASS '+String(e.recordingSerial).padStart(2,'0'):(labels[e.category]||'RESOURCE'),title(e),isClass?(e.topicVerification||'ক্লাসের টপিক ও পূর্ণ রিসোর্স তালিকা পরবর্তী ধাপে যাচাই করে যোগ হবে।'):null);
 const layout=node('div',null,'class-detail-layout'),main=node('section'),aside=node('aside',null,'panel detail-sidebar');const youtube=e.youtubeId||(e.videoStatus==='uploaded-processing'?e.pendingYoutubeId:null);if(youtube&&/^[\w-]{11}$/.test(youtube)){if(!e.youtubeId)main.append(strip('YouTube processing চলছে। প্রস্তুত হলে এই প্লেয়ারেই ভিডিও দেখা যাবে।'));const f=node('iframe',null,'player');f.src='https://www.youtube-nocookie.com/embed/'+youtube;f.title=title(e);f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';f.allowFullscreen=true;main.append(f);}else if(isClass||e.category==='classes'){const box=node('div',null,'player-placeholder');append(box,node('span','▷','play-circle'),node('h3',status(e).text),node('p',e.videoStatus==='uploading'?'শুরু করা আপলোডের কাজ সংরক্ষিত আছে। যাচাই করা ভিডিও এখানে যুক্ত হলে সাইটের ভেতরেই দেখা যাবে।':'এই ক্লাসের ভিডিও রাখার জায়গা প্রস্তুত। YouTube লিংক যোগ হলে এখানেই প্লে হবে।'));main.append(box);}
 const meta=node('div',null,'detail-meta');for(const [label,value]of [[isClass?'রেকর্ডের তারিখ':'পোস্টের তারিখ',date(e.date)],[e.classStartTime?'পোস্টে দেওয়া সময়':'নিয়মিত ক্লাসের সময়',e.classStartTime||e.scheduledTime||'সময় যাচাই বাকি'],['ভিডিওর দৈর্ঘ্য',e.duration||'পরে যোগ হবে']])append(meta,append(node('div'),node('span',label),node('strong',value)));main.append(meta);const tabs=node('div',null,'detail-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','ক্লাসের রিসোর্স');const tabContent=node('section',null,'detail-tab-content');tabContent.id='detail-tab-content';tabContent.setAttribute('role','tabpanel');let selected=params.get('tab')||'overview';if(!['overview','notes','documents','tools'].includes(selected))selected='overview';
 function drawTab(name){selected=name;tabs.querySelectorAll('button').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active)tabContent.setAttribute('aria-labelledby',b.id);});tabContent.replaceChildren();const related=relatedResources(e);
  if(name==='overview'){tabContent.append(node('h3','ক্লাসের তথ্য'));if(e.topic)tabContent.append(node('p','বিষয়: '+(e.topicTitle||e.topic),'muted'));if(e.text)tabContent.append(textWithLinks(e.text));if(e.scheduledTime&&!e.classStartTime)tabContent.append(strip('উপরের সময় সাপ্তাহিক শিডিউল অনুযায়ী। এই রেকর্ডের প্রকৃত শুরুর সময় যাচাই বাকি।'));const slots=node('div',null,'slot-grid');append(slots,slot('ক্লাস ভিডিও',youtube?'সাইটের প্লেয়ারে ভিডিও যুক্ত আছে।':'ভিডিওর জায়গা প্রস্তুত; যাচাই করা ভিডিও পরে যোগ হবে।','video',e.id,!!youtube),slot('ক্লাস নোট',[e,...related].some(x=>x.noteText)?'পূর্ণ নোট “নোট” ট্যাবে পড়া যাবে।':'ক্লাসের সারাংশ ও লিখিত নোট পরে যোগ হবে।','note',e.id,[e,...related].some(x=>x.noteText)),slot('ডকুমেন্ট',related.some(x=>x.category==='documents')?'সংশ্লিষ্ট ডকুমেন্ট “ডকুমেন্ট” ট্যাবে আছে।':'PDF, স্লাইড ও প্রয়োজনীয় ফাইল পরে যোগ হবে।','document',e.id,related.some(x=>x.category==='documents')),slot('টুলস ও সেটআপ',related.some(x=>x.category==='tools')?'সংশ্লিষ্ট টুলস “টুলস” ট্যাবে আছে।':'প্রয়োজনীয় টুলস ও সেটআপ নির্দেশনা পরে যোগ হবে।','tool',e.id,related.some(x=>x.category==='tools')));tabContent.append(slots);resourceLinks(e,tabContent);if(e.classDate)tabContent.append(node('p','সংশ্লিষ্ট ক্লাসের তারিখ: '+date(e.classDate),'muted'));}
  if(name==='notes')notesView(e,tabContent);
  if(name==='documents'||name==='tools'){const category=name==='documents'?'documents':'tools';const relevant=related.filter(x=>x.category===category);if(e.category===category)relevant.unshift(e);if(relevant.length){for(const x of relevant){const p=node('section',null,'note-content');p.append(node('h3',title(x)));if(x!==e)p.append(internal(resourceHash(x),'বিস্তারিত দেখুন ↗','text-link'));if(x.text)p.append(textWithLinks(x.text));resourceLinks(x,p);tabContent.append(p);}}else tabContent.append(slot(name==='documents'?'ক্লাস ডকুমেন্ট পরে যোগ হবে':'ক্লাসের টুলস পরে যোগ হবে',name==='documents'?'PDF, স্লাইড, ক্লাস ফাইল ও অন্যান্য ডকুমেন্ট এখানে রাখার জায়গা প্রস্তুত।':'এই ক্লাসের প্রয়োজনীয় টুল, সেটআপ গাইড ও ব্যবহারবিধি এখানে রাখা যাবে।',name==='documents'?'document':'tool',e.id));}
 }
 for(const [key,label]of [['overview','ক্লাসের তথ্য'],['notes','নোট'],['documents','ডকুমেন্ট'],['tools','টুলস']]){const b=button(label,()=>drawTab(key));b.dataset.tab=key;b.id='tab-'+key;b.setAttribute('role','tab');b.setAttribute('aria-controls','detail-tab-content');b.onkeydown=event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const children=[...tabs.children],index=children.indexOf(b);const next=event.key==='Home'?0:event.key==='End'?children.length-1:(index+(event.key==='ArrowRight'?1:-1)+children.length)%children.length;drawTab(children[next].dataset.tab);children[next].focus();}};tabs.append(b);}main.append(tabs,tabContent);drawTab(selected);
 if(isClass){aside.append(node('p','COURSE CONTENT','eyebrow'),node('h3','সব ক্লাস'));const rows=node('div',null,'class-list');records().forEach(x=>rows.append(classRow(x,true)));aside.append(rows);const sorted=records(),index=sorted.findIndex(x=>x.id===e.id),navigation=node('div',null,'detail-prev-next');if(index>0)navigation.append(internal(resourceHash(sorted[index-1]),'← আগের ক্লাস','button'));if(index<sorted.length-1)navigation.append(internal(resourceHash(sorted[index+1]),'পরের ক্লাস →','button primary'));main.append(navigation);}else{aside.append(node('h3','রিসোর্সের তথ্য'),node('p',labels[e.category]||'রিসোর্স','muted'),node('p',e.author||'Arena B66 Delta','muted'),badge(e),internal('#manage?class='+e.id,'＋ নতুন রিসোর্সের খসড়া','resource-link'));}append(layout,main,aside);$('page').append(layout);
}
function schedule(){heading('CLASS CALENDAR','ক্লাসের সময়সূচি','নিয়মিত ক্লাস ও সাপোর্টের সময় দেখুন। নিচের তালিকায় সংগ্রহ করা রেকর্ডের তারিখ দেখানো আছে।');$('page').append(weekly(),strip(archive.schedule?.timeZoneNote||'পোস্টে সময় অঞ্চল উল্লেখ নেই।'),external(archive.schedule?.source,'অফিশিয়াল সময়সূচির মূল পোস্ট ↗'));$('page').append(sectionHeading('তারিখ অনুযায়ী ক্লাস রেকর্ড'));const month=node('select');month.setAttribute('aria-label','ক্যালেন্ডারের মাস বাছাই');month.append(new Option('সব মাস',''));for(const m of [...new Set(records().map(e=>e.date?.slice(0,7)).filter(Boolean))].sort())month.append(new Option(new Intl.DateTimeFormat('bn-BD',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T00:00:00Z')),m));const bar=node('div',null,'filter-bar');bar.append(month);$('page').append(bar);const grid=node('div',null,'calendar-grid');function draw(){grid.replaceChildren();for(const e of records().filter(e=>!month.value||(e.date||'').startsWith(month.value))){const a=node('article',null,'calendar-item');append(a,node('div',date(e.date,false),'calendar-date'),node('span','রেকর্ড #'+bn(e.recordingSerial),'eyebrow'),node('h3',title(e)),node('p',e.classStartTime?'পোস্টে দেওয়া সময়: '+e.classStartTime:'সাপ্তাহিক সময়: রাত ৯:৩০–১১:৩০ · প্রকৃত সময় যাচাই বাকি'),internal(resourceHash(e),'ক্লাসের বিস্তারিত ↗','text-link'));grid.append(a);}}month.onchange=draw;draw();$('page').append(grid);}
function youtubeId(value){if(/^[\w-]{11}$/.test(value))return value;try{const u=new URL(value);if(u.hostname==='youtu.be')return /^[\w-]{11}$/.test(u.pathname.slice(1))?u.pathname.slice(1):null;if(['youtube.com','www.youtube.com','www.youtube-nocookie.com'].includes(u.hostname)){const id=u.searchParams.get('v')||u.pathname.split('/')[2];return /^[\w-]{11}$/.test(id||'')?id:null;}}catch{}return null;}
function downloadJSON(data,filename){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));const a=node('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function manage(params){heading('CONTENT WORKSPACE','রিসোর্স যোগ করার জায়গা','ক্লাসের ভিডিও, নোট, ডকুমেন্ট বা টুলসের খসড়া তৈরি করুন। খসড়া JSON ডাউনলোড করে GitHub-এর data.json আপডেট করলে সাইটে প্রকাশ হবে।');$('page').append(strip('এই ফর্ম খসড়া তৈরি করে। এখান থেকে সরাসরি প্রকাশ বা YouTube-এ আপলোড হয় না। খসড়া ডাউনলোড করুন; পেজ বন্ধ করলে সংরক্ষণ না করা খসড়া হারাবে।'));
 const layout=node('div',null,'form-layout'),panel=node('section',null,'panel'),form=node('form',null,'editor-form');panel.append(node('h3','নতুন রিসোর্সের খসড়া'));const inputs={};function field(key,label,type='text',options){const l=node('label',label),i=node(type==='textarea'?'textarea':type==='select'?'select':'input');if(type!=='textarea'&&type!=='select')i.type=type;i.name=key;inputs[key]=i;if(options)for(const [value,text]of options)i.append(new Option(text,value));l.append(i);return l;}
 const kind=field('kind','রিসোর্সের ধরন','select',[['video','ক্লাসের YouTube ভিডিও'],['note','লিখিত নোট'],['document','ডকুমেন্ট / PDF লিংক'],['tool','টুল ও সেটআপ লিংক'],['class','নতুন ক্লাসের জায়গা']]);const classField=field('classId','কোন ক্লাসের সঙ্গে থাকবে?','select',[['','স্বতন্ত্র রিসোর্স'],...records().map(e=>[e.id,'#'+String(e.recordingSerial).padStart(2,'0')+' · '+title(e)])]);if(params.get('class')&&records().some(e=>e.id===params.get('class')))inputs.classId.value=params.get('class');inputs.kind.value=['video','note','document','tool','class'].includes(params.get('kind'))?params.get('kind'):'video';const titleField=field('title','শিরোনাম');inputs.title.placeholder='রিসোর্স বা ক্লাসের নাম';const pair=append(node('div',null,'form-two'),field('date','তারিখ (জানা থাকলে)','date'),field('time','ক্লাসের সময় (জানা থাকলে)','time'));const linkField=field('url','YouTube বা রিসোর্সের লিংক');inputs.url.placeholder='https://…';const textField=field('text','নোট বা বিস্তারিত তথ্য','textarea');const message=node('p',null,'editor-message');message.setAttribute('role','status');const submit=node('button','＋ খসড়ায় যোগ করুন','button primary');submit.type='submit';append(form,kind,classField,titleField,pair,linkField,textField,submit,message);panel.append(form);
 const aside=node('aside',null,'panel');aside.append(node('h3','প্রকাশ করার পদ্ধতি'));const steps=node('ol',null,'step-list');for(const t of ['ক্লাস ও রিসোর্সের ধরন বেছে লিংক বা নোট যোগ করুন।','সম্পূর্ণ আপডেট করা JSON খসড়া ডাউনলোড করুন।','GitHub repository-র data.json-এ পর্যালোচনা করা খসড়া বসিয়ে commit করুন। Vercel থেকে সাইট আপডেট হবে।'])steps.append(node('li',t));aside.append(steps,node('p','Unlisted YouTube ভিডিও সাইটে প্লে হবে। Private ভিডিও সবার জন্য দেখা যাবে না।','muted'));const draftList=node('div',null,'draft-list');const exportButton=button('আপডেট করা JSON ডাউনলোড ↓',()=>{const result=JSON.parse(JSON.stringify(archive));for(const draft of drafts){if(draft.kind==='video'){const target=result.entries.find(e=>e.id===draft.classId);if(target){target.youtubeId=draft.youtubeId;target.videoStatus='ready';target.playbackVerified=false;target.pendingYoutubeId=null;}}else{const e={id:draft.id,title:draft.title,author:'Archive editor',date:draft.date||null,classDate:draft.date||null,classStartTime:draft.time||null,text:draft.text,links:draft.url?[draft.url]:[],category:draft.kind==='class'?'recordings':draft.kind==='tool'?'tools':'documents',topic:null,videoStatus:draft.kind==='class'?'upload-pending':'not-applicable',youtubeId:null,truncated:false,collectionIndex:result.entries.length,dateVerified:false};if(draft.kind==='note')e.noteText=draft.text;if(draft.kind==='class')e.recordingSerial=result.entries.filter(e=>e.category==='recordings').length+1;if(draft.classId){e.relatedRecordingId=draft.classId;const target=result.entries.find(e=>e.id===draft.classId);if(target){target.relatedResourceIds=[...(target.relatedResourceIds||[]),e.id];e.classDate=target.date;}}result.entries.push(e);}}result.updatedAt=new Date().toISOString();downloadJSON(result,'archive-data-draft.json');notify('আপডেট করা JSON খসড়া ডাউনলোড হয়েছে।');},'button primary');aside.append(node('h3','আপনার খসড়া'),draftList,exportButton,button('খালি রিসোর্স টেমপ্লেট ↓',()=>downloadJSON({title:'',classId:'',kind:'document',date:'',url:'',text:''},'resource-template.json'),'button'));
 function drawDrafts(){draftList.replaceChildren();exportButton.disabled=!drafts.length;if(!drafts.length)draftList.append(node('p','এখনো কোনো খসড়া যোগ হয়নি।','muted'));for(const d of drafts){const box=append(node('div',null,'draft-item'),node('strong',d.title),node('p',({video:'YouTube ভিডিও',note:'নোট',document:'ডকুমেন্ট',tool:'টুল',class:'নতুন ক্লাস'})[d.kind]),button('খসড়া সরান',()=>{drafts=drafts.filter(x=>x.id!==d.id);drawDrafts();}));draftList.append(box);}}
 form.onsubmit=event=>{event.preventDefault();message.className='editor-message';message.textContent='';const values=Object.fromEntries(Object.entries(inputs).map(([key,i])=>[key,i.value.trim()]));const selected=entries.find(e=>e.id===values.classId);const ytId=values.kind==='video'?youtubeId(values.url):null;let error='';if(values.kind==='video'&&(!selected||!ytId))error='ভিডিওর জন্য একটি ক্লাস এবং সঠিক YouTube লিংক বা ID দিন।';if(['document','tool'].includes(values.kind)&&(!values.title||!safeURL(values.url)||!/^https?:\/\//i.test(values.url)))error='শিরোনাম এবং সম্পূর্ণ https লিংক দিন।';if(values.kind==='note'&&(!values.title||!values.text))error='নোটের শিরোনাম এবং লেখা দিন।';if(values.kind==='class'&&(!values.title||!values.date))error='নতুন ক্লাসের শিরোনাম এবং রেকর্ডের তারিখ দিন।';if(error){message.textContent=error;message.classList.add('error-message');return;}drafts.push({...values,id:'draft-'+Date.now()+'-'+drafts.length,title:values.title||title(selected),youtubeId:ytId});message.textContent='খসড়া যোগ হয়েছে। প্রকাশের জন্য JSON ডাউনলোড করুন।';message.classList.add('success-message');drawDrafts();};drawDrafts();append(layout,panel,aside);$('page').append(layout);
}
function about(){heading('ABOUT THE ARCHIVE','শেখার জন্য সাজানো একটি জায়গা','Arena Web Security · Batch 66 Delta');const grid=node('div',null,'about-grid');for(const [h,p]of [['ক্লাসের ধারাবাহিকতা','ক্লাস রেকর্ড আলাদা সিরিয়াল অনুযায়ী সাজানো। collectionIndex পোস্ট সংগ্রহের ক্রম; সেটি ক্লাস নম্বর হিসেবে দেখানো হয় না।'],['পরে রিসোর্স যোগ করা যাবে','প্রতিটি ক্লাসে ভিডিও, নোট, ডকুমেন্ট ও টুলসের জায়গা আছে। খসড়া ফর্ম ও JSON টেমপ্লেট ব্যবহার করে নতুন রিসোর্স যোগ করা যাবে।'],['তারিখ ও সময়ের তথ্য','যাচাই না হওয়া পোস্টের তারিখ আলাদাভাবে দেখানো হয়। রেকর্ডের তারিখ ও সাপ্তাহিক শিডিউল দেখানো আছে; প্রকৃত ক্লাসের সময় নিশ্চিত হলে যুক্ত হবে।'],['ভিডিও দেখার ব্যবস্থা','যুক্ত YouTube ভিডিও ওয়েবসাইটের ভেতরেই প্লে হবে। বাকি ভিডিওর জন্য প্রস্তুত জায়গা আছে। Facebook সোর্স লিংক দেখতে সদস্যপদ প্রয়োজন হতে পারে।']])grid.append(append(node('article',null,'panel'),node('h3',h),node('p',p)));$('page').append(grid,strip('ওয়েবসাইটের কাঠামো প্রস্তুত। কোর্সের সব রিসোর্স সংগ্রহ ও তারিখ যাচাই এখনো সম্পূর্ণ নয়।'),external('https://github.com/mdnhbn/arena-b66-delta-archive','সাইটের GitHub repository ↗'));}
function route(){if(!archive)return;const raw=location.hash.slice(1)||'overview';const [path,query='']=raw.split('?');const parts=path.split('/');const params=new URLSearchParams(query);let view=parts[0],id=parts[1];if(view.startsWith('entry-')){id=view;view=entries.find(e=>e.id===id)?.category==='recordings'?'class':'resource';}if(!pageNames[view])view='overview';currentPage=view;document.title=(pageNames[view]||'Delta Archive')+' · Arena B66';$('breadcrumb-current').textContent=pageNames[view];$('page').replaceChildren();document.querySelectorAll('[data-page]').forEach(a=>{const active=a.dataset.page===view||(view==='class'&&a.dataset.page==='classes')||(view==='resource'&&a.dataset.page==='resources');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('sidebar').classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0);if(view==='overview')overview();else if(['classes','resources','tools','notices'].includes(view))collection(view,params);else if(view==='schedule')schedule();else if(view==='manage')manage(params);else if(view==='about')about();else if(view==='class'||view==='resource'){const e=entries.find(x=>x.id===id);if(e)detail(e,params);else $('page').append(empty('এই রিসোর্সটি পাওয়া যায়নি','লাইব্রেরি থেকে একটি ক্লাস বা রিসোর্স বেছে নিন।','#resources'));}}
function closeMenu(){$('sidebar').classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false');$('menu-toggle').setAttribute('aria-label','মেনু খুলুন');}
$('menu-toggle').onclick=()=>{const open=$('sidebar').classList.toggle('open');$('menu-toggle').setAttribute('aria-expanded',String(open));$('menu-toggle').setAttribute('aria-label',open?'মেনু বন্ধ করুন':'মেনু খুলুন');};document.addEventListener('click',e=>{if($('sidebar').classList.contains('open')&&!$('sidebar').contains(e.target)&&!$('menu-toggle').contains(e.target))closeMenu();});$('sidebar').querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});window.addEventListener('hashchange',route);
fetch('data.json').then(r=>{if(!r.ok)throw Error('Data unavailable');return r.json();}).then(data=>{if(!Array.isArray(data.entries))throw Error('Invalid archive');archive=data;entries=data.entries;$('class-count').textContent=bn(records().length);route();}).catch(()=>{$('page').replaceChildren(empty('তথ্য লোড হয়নি','পেজটি আবার খুলুন। সাইটের কাঠামো ও রিসোর্স আলাদাভাবে সংরক্ষিত আছে।'));});
